ShopDongHo/ShopDongHo/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopDongHo.Models;

namespace ShopDongHo.Controllers
{
    public class GioHangController: Controller
    {
        private ShopDongHoEntities db = new ShopDongHoEntities();
        // GET: GioHang
       
        public ActionResult Index()
        {        
            return View();
        }

        // GET: GioHang/ThemVaoGio/{maSP}
        public ActionResult ThemVaoGio(int maSP)
        {
            if (Session["cart"] == null)
            {
                var sp = db.DongHo.Find(maSP);
                List<SanPhamTrongGio> cart = new List<SanPhamTrongGio>();
                cart.Add(new SanPhamTrongGio { dongho = sp, soLuongTrongGio = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
                int index = isExist(maSP);
                if (index != -1)
                {
                    cart[index].soLuongTrongGio++;
                }
                else
                {
                    var sp = db.DongHo.Find(maSP);
                    cart.Add(new SanPhamTrongGio { dongho = sp, soLuongTrongGio = 1 });
                }
                Session["cart"] = cart;
            }

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatTang/{maSP}
        public ActionResult CapNhatTang(int maSP)
        {
            var sp = db.DongHo.Find(maSP);
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio <= 10)
                    if(item.soLuongTrongGio < sp.SoLuong)
                    {
                        item.soLuongTrongGio++;
                    }
                    else
                    {
                        TempData["Message"] = "Sản phẩm không đủ số lượng hiện có " + sp.SoLuong;
                    }
                    
            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/CapNhatGiam/{maSP}
        public ActionResult CapNhatGiam(int maSP)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.dongho.ID == maSP && item.soLuongTrongGio >= 1)
                    item.soLuongTrongGio--;
            }
            Session["cart"] = cart;

            return RedirectToAction("Index");
        }

        // GET: GioHang/XoaKhoiGio/{maSP}
        public ActionResult XoaKhoiGio(int maSP)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            int index = isExist(maSP);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<SanPhamTrongGio> cart = (List<SanPhamTrongGio>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].dongho.ID.Equals(id))
                    return i;
            return -1;
        }
    }
}

ShopDongHo/ShopDongHo/Views/GioHang/Index.cshtml
@model IEnumerable<ShopDongHo.Models.DongHo>

@{
    ViewBag.Title = "Giỏ hàng";
    var cart = (List<ShopDongHo.Models.SanPhamTrongGio>)Session["cart"];
    
}

<div class="card mt-3">
    <h5 class="card-header">@ViewBag.Title</h5>
    <div class="card-body">
        @if (cart == null || cart.Count <= 0)
        {
            <span class="alert alert-danger">Giỏ hàng chưa có sản phẩm!</span>
        }
        else
        {
            {
                string message = TempData["Message"] as string;
                if (message != null)
                {
                    <p class="alert alert-danger">@message</p>
                }
            }

        <table class="table table-bordered table-hover table-sm">
            <tr>
                <th width="5%">#</th>
                <th>Hình ảnh</th>
                <th>Sản phẩm</th>
                <th width="10%">Số lượng</th>
                <th>Đơn giá</th>
                <th>Thành tiền</th>
                <th width="5%"></th>
            </tr>
            @{ int stt = 1; }
            @foreach (var item in cart)
            {
                <tr>
                    <td>@stt</td>
                    <td><img src="~/@item.dongho.HinhAnhDH" width="50" /></td>
                    <td>@item.dongho.TenDongHo</td>
                    <td>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><a href="@Url.Action("CapNhatGiam", "GioHang", new { maSP = item.dongho.ID })"><i class="fas fa-minus"></i></a></span>

                            </div>
                            <input type="text" class="form-control text-center" value="@item.soLuongTrongGio" readonly />
                            <div class="input-group-append">
                                <span class="input-group-text"><a href="@Url.Action("CapNhatTang", "GioHang", new { maSP = item.dongho.ID })"><i class="fas fa-plus"></i></a></span>
                            </div>
                        </div>
                    </td>
                    <td class="text-right">@String.Format("{0:N0}", item.dongho.DonGia) VNĐ</td>
                    <td class="text-right">@String.Format("{0:N0}", item.soLuongTrongGio * item.dongho.DonGia) VNĐ</td>
                    <td class="text-center"><a href="@Url.Action("XoaKhoiGio", "GioHang", new { maSP = item.dongho.ID })">Xóa</a></td>
                </tr>
                stt++;
            }

            <tr>
                <td colspan="5">Tổng thành tiền</td>
                <td class="text-right font-weight-bold text-primary">
                    @{
                        var total = @String.Format("{0:N0}", cart.Sum(item => item.dongho.DonGia * item.soLuongTrongGio)) + " VNĐ";
                    }
                    @total
                </td>
                <td></td>
            </tr>
        </table>

        <p>
            <a href="@Url.Action("Index", "Home")" class="btn btn-primary">Tiếp tục mua hàng</a>
            <a href="@Url.Action("ThanhToan", "Home")" class="btn btn-success">Thanh toán</a>
        </p>
    }
    </div>
</div>